VAGRANTFILE_API_VERSION = "2"
#Refer to ND1.bmp for network topology refernce

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  config.vm.box = "ubuntu/trusty64"

    #net1 - 192.168.10.0/24
    #net1mc1	
    config.vm.define :net1mc1 do |net1mc1|
    net1mc1.vm.provider "virtualbox" do |v|
      #v.vmx["memsize"]  = "2048"
      #very useful to debug when VM start up gets stuck. This command will open up a console, and show the output as the VM gets installed.
	 #v.gui = true 
    end
    net1mc1.vm.provider :virtualbox do |v|
      v.name = "net1mc1"
      v.customize ["modifyvm", :id, "--memory", "2048"]
      #v.gui = true

    end
    net1mc1.vm.network :private_network, ip: "192.168.10.12"
    net1mc1.vm.hostname = "net1mc1"
    net1mc1.vm.provision :shell, path: "target/scripts/install.sh"
    end
    
     #net1 - 192.168.10.0/24
     #net1mc2	
     config.vm.define :net1mc2 do |net1mc2|
     net1mc2.vm.provider "virtualbox" do |v|
       #v.vmx["memsize"]  = "2048"
       #very useful to debug when VM start up gets stuck. This command will open up a console, and show the output as the VM gets installed.
	 #v.gui = true 
     end
     net1mc2.vm.provider :virtualbox do |v|
       v.name = "net1mc2"
       v.customize ["modifyvm", :id, "--memory", "2048"]
       #v.gui = true

     end
     net1mc2.vm.network :private_network, ip: "192.168.10.13"
     net1mc2.vm.hostname = "net1mc2"
     net1mc2.vm.provision :shell, path: "target/scripts/install.sh"
    end
    
    #net1 - 192.168.10.0/24
    #net1mc3	
    config.vm.define :net1mc3 do |net1mc3|
    net1mc3.vm.provider "virtualbox" do |v|
      #v.vmx["memsize"]  = "2048"
      #very useful to debug when VM start up gets stuck. This command will open up a console, and show the output as the VM gets installed.
	 #v.gui = true 
    end
    net1mc3.vm.provider :virtualbox do |v|
      v.name = "net1mc3"
      v.customize ["modifyvm", :id, "--memory", "2048"]
      #v.gui = true

    end
    net1mc3.vm.network :private_network, ip: "192.168.10.14"
    net1mc3.vm.hostname = "net1mc3"
    net1mc3.vm.provision :shell, path: "target/scripts/install.sh"
    end

   #workstation	
    config.vm.define :workstation do |workstation|
     workstation.vm.provider :virtualbox do |v|
      v.name = "workstation"
      v.customize ["modifyvm", :id, "--memory", "1048"]
      #v.gui = true

    end
    workstation.vm.network :private_network, ip: "192.168.50.11"
    workstation.vm.hostname = "workstation"
    workstation.vm.provision :shell, path: "target/scripts/install_ws.sh"
    end



end